---
version: '3.5'
services:
  shared-database:
    image: postgres:12.4
    environment:
      DB_USERNAME:
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 6432:5432
  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx400m
      - ES_JAVA_OPTS= -Xms128m -Xmx400m
      - cluster.name=ccd-docker-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*,grantofrepresentation_cases,caveat_cases,legacy_cases,standingsearch_cases,willlodgement_cases
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  ccd-logstash:
    image: hmctspublic.azurecr.io/ccd/logstash:ccd-divorce-logstash-latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx400m
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://shared-database:5432/postgres?stringtype=unspecified&ssl=false&currentSchema=datastore
      - DB_USER=postgres
      - DB_PWD=postgres
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
      - LOG_LEVEL=warn
    depends_on:
      - ccd-elasticsearch
      - shared-database

